### PR TITLE
added Redis TimeSeries tsadd function to library

### PR DESCRIPTION
**Pull request by gde-2**
as asked in the discussion "support for timeseries"

### CODE REVIEW

**Comment by rpj** [comment]
Excellent work and my sincere appreciation for your contribution to the project @gde-2! 🙌 ❤️ 

The code looks great, I'm happy to merge it straightaway!

**Review by rpj — APPROVED** [review]

**Comment by rpj** [comment]
In order to give you primary credit on the commit, you should merge this instead of me: if I do, I'll be the author and you the "Co-Author". Simply click the "Squash and Merge" button then "Confirm squash and merge" (the commit message it fills in is fine), and that's it! Once it lands I'll fix up the repo for a new release and your change will be available soon in version `2.4.3`!

**Comment by gde-2** [comment]
Thanks for your kindness.
I do not see a button to merge into the main branch, maybe I'm looking in the wrong place but to me it looks more like I do not have the permission to do so.

**Comment by rpj** [comment]
Oh geez... I could have sworn I already added you as a contributor, but apparently I had not. 🤦 My apologies for the confusion on that!

I've properly invited you with "write" access now, you should have the invite in your inbox and (as I understand it) once you accept that you'll have the buttons I mentioned and will be able to merge the PR. 👍

**Pull request merged**
